### ISSUE TITLE
[WARN] Container 0 height reported, possible bug in LegendList

### ISSUE THREAD

**Issue by DanielSRS** [LegendApp/legend-list#133]
Just updated from 1.0.0-beta.11 to 1.0.0-beta.15 and start seeing this logs and items positions not updating when the list changes:

| 1.0.0-beta.11  | 1.0.0-beta.15 |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/7a0d9fdc-1c17-4f0f-b684-3ed65ef75677" /> | <video src="https://github.com/user-attachments/assets/df3febee-963e-4999-83e7-c0f0486de016" /> |

Code:
```tsx
<Memo>
  {() => {
    return (
      <LegendList
        data={tabIds.get()}
        style={fatlist}
        ref={listRef}
        contentContainerStyle={fatlistContent}
        renderItem={renderItem}
        keyExtractor={i => i}
        estimatedItemSize={36}
      />
    );
  }}
</Memo>

```

### Platform and version

- I am running this on `react-native-macos 0.76`
- and the `old arch`

> [!NOTE]
> **I didint test this on android or ios, nor the new arch** so theres a chance that this is a macos only bug. 

I will try to reproduce this on mobile later

**Comment by jmeistrich** [comment]
Oh wow are you making a React Native browser? That's awesome!

I actually just spun up a react-native-macos app myself and encountered the "Container 0 height reported" warning. So I'll try to fix that asap. 

But I believe the positions not updating might be because of the keyExtractor returning the index. Can you try either removing that or returning a unique id for each tab?

**Comment by jmeistrich** [comment]
Hmm, it looks like it was logging that warning too aggressively on react-native-macos, so that was not a real problem. In the next update the aggressiveness of that log will be turned down so you won't see it anymore.

So I think the problem here is likely the keyExtractor. Would I be able to reproduce it if I clone the repo and bump the list version?

**Comment by DanielSRS** [comment]
> Oh wow are you making a React Native browser? That's awesome!

Actually I am, but its very simple right now. Just testing things out 😅

> might be because of the keyExtractor returning the index

Oh, sorry. That name is actually a bit misleading, but that is the id not the index. I am doing something like you suggested here  https://github.com/LegendApp/legend-list/issues/108#issuecomment-2676550472 and passing an ID list to LegendList and consuming the observables by id in the renderItem.

- **If I remove the keyExtractor, then when I remove an item, it just removes the last item instead of the one I deleted.**

> Would I be able to reproduce it if I clone the repo and bump the list version?

Yes!, [here is the repo](https://github.com/DanielSRS/BrowserUI) and [here is the file with the list](https://github.com/DanielSRS/BrowserUI/blob/main/src/components/Tabbar/tab-bar.tsx). When I was testing, the list version was the only diff.

**Comment by DanielSRS** [comment]
I finally found some time to set a proper repro of the issue with expo snack.

- The issue seems to happen when I delete the first item of the list. Otherwise everything seems to work as expected.
- I was able reproduce the issue on web and the expo go (android) with SDK 52

[Here's the snack link](https://snack.expo.dev/@daniel.srs/legend_list_issue_133_repro)

https://github.com/user-attachments/assets/8d2b5b36-1522-4e3e-8e5d-769ff1eac919

**Comment by marcel-happyfloat** [comment]
I'm also facing this issue, but in a different context. I get a blank screen (no scrolling possible) after calling:

```ts
scrollViewRef.current?.scrollToIndex({
         index: targetIndex,
         animated: true,
         viewPosition: 0.5, // not yet supported?
});
```

It goes immediately blank without animating anything. The interesting part is, that after a hot reload, the list appears again at the correct new scroll position!

**Comment by jmeistrich** [comment]
@marcel-happyfloat `viewPosition` is not yet supported. I'll see if we can get that in soon, tracking it in https://github.com/LegendApp/legend-list/issues/146

Does this scrollToIndex work correctly without the `viewPosition` parameter? If not that would be a big bug!

Does `viewPosition` somehow work correctly in AnimatedLegendList? Its purpose is for binding properties to `Animated` values, but if not doing that it shouldn't behave any differently...  It's just a wrapper around `Animated.createAnimatedComponent`, but the Reanimated equivalent does more work adjusting refs.

It's just that the documentation hasn't caught up yet to the latest features as we're putting all of our time into finishing the 1.0 blocking bugs. That's on my list of things to document before 1.0.

**Comment by marcel-happyfloat** [comment]
Hey @jmeistrich, thanks for the response! I tried adding and removing the parameter, but it didn’t seem to make a difference.

As mentioned above, it scrolls correctly either way, but ends up showing a blank/white screen and gets stuck there. It could be something specific to my setup, but after a hot reload, it reappears at the correct scroll position. Using Animated or the Reanimated export directly avoids the blank screen and works as expected.

viewPosition would definitely be a nice addition, but for me personally, a working sticky header implementation would be even more valuable 🙏

Thank you very much!

**Comment by jmeistrich** [comment]
Huh, that's fascinating. I'm not sure why the animated version would perform differently...

I've got some updates in progress to:

- fix issues with items being 0 height: are your items rendering conditionally or are there any cases where they might be either not rendering anything or rendering something with 0 height? That currently does some weird things but will be fixed in the next update.
- add viewPosition

**Comment by marcel-happyfloat** [comment]
No, they always render something.

**Comment by jmeistrich** [comment]
Hmm okay, that's wild! I'll aim to release that update tomorrow which hopefully will fix it. If not we can dig deeper.

**Comment by jmeistrich** [comment]
@DanielSRS I think this is fixed now in beta.25. I just tested updating your snack to beta.25 and it looks like it's working correctly now. Can you try updating and see if it works better for you?

**Comment by jmeistrich** [comment]
@marcel-happyfloat Can you test beta.25 and see if this is fixed for you (without needing the Animated version)? If not, can you share more of your code that I can use to test with?

**Comment by DanielSRS** [comment]
@jmeistrich I updated and its working great! No more positioning issues nor warnings.

Thank you! 🚀

**Comment by marcel-happyfloat** [comment]
@jmeistrich it's still not fixed, but the error message is different. When I try to scroll the blank screen, this error message appears: `[legend-list] No container to recycle, so creating one on demand. This can be a minor performance issue and is likely caused by the estimatedItemSize being too large. Consider decreasing estimatedItemSize. numContainers: 27
﻿`

I tried simplifying things and experimenting a bit in my code, and it started behaving unpredictably—content was jumping around, overlapping, some items disappeared and it got stuck.

Reanimated version worked in all these cases flawlessly (as did the animated version when I tested initially).
Also, viewPosition is working now 💯❤️ — thank you for that!

I’m currently on a tight schedule, but I hope I can share a minimal repro soon to help dig into this further.

**Comment by jmeistrich** [comment]
@marcel-happyfloat Can you try enabling the `maintainVisibleContentPosition` if it's not already and see if that improves it for you? Or if it is enabled, does disabling it change the behavior?

**Comment by marcel-happyfloat** [comment]
@jmeistrich,
It doesn't seem to make any difference.

I just checked the source code of LegendList to look for any differences myself, and simply wrapping it with Animated.createAnimatedComponent(LegendList) fixes the issue. So I strongly suspect it's related to Reanimated beta, react-native-screens, or something else in the stack—I'm on RN 0.77.1 with the new architecture.

Go ahead and close this issue for now. I'll report back if anything changes or if I get the chance to put together a repro. Since it works with the animated version, it's not that critical.

**Comment by jmeistrich** [comment]
Hmm okay. It didn't make sense to me that the animated versions would fix whatever the problem is, but I could see it being caused by a combination with other things in the stack...

Yeah I'll close this issue, and please let me know and post another issue if you're able to track down the cause.
