### ISSUE TITLE
Blank area at the bottom for a single frame (infinite scrolling)

### ISSUE THREAD

**Issue by BorislavStefanov31** [LegendApp/legend-list#207]
There is a blank area at the bottom of the screen for a single frame when new items are being added.

**Comment by jmeistrich** [comment]
Can you share some more details? A video, a repository I could test?

**Comment by BorislavStefanov31** [comment]
When I append 15 new items to my data source upon reaching the end of the list, I'm experiencing a brief rendering inconsistency. The sequence occurs as follows:

1. The list is rendered with 15 initial items
2. User scrolls to the bottom of the list
3. onEndReached callback triggers fetching of 15 additional items
4. Issue: For a single frame, empty space appears at the bottom of the list
5. After this momentary delay, the new items render correctly

It appears to me that the list container is allocating space for the new items before the actual content renders, causing this brief "flash" of empty space that can be scrolled into.

**Comment by jmeistrich** [comment]
Is this on new or old architecture?

**Comment by jmeistrich** [comment]
Huh, that is wild. It updates the total size in the onLayout after an element renders, so I don't know how it could do that before it renders...

I just released 1.0.4 which fixes a bunch of old architecture things - could you try upgrading and see if that fixes it?

Otherwise is it possible to create a reproduction that I could use to test and fix it?

**Comment by BorislavStefanov31** [comment]
Here is a video of a demo list with the bug happening (item's have very expensive calculations inside of them: 

https://github.com/user-attachments/assets/47844dbf-3cb0-4667-b895-846941efba0f

I also made a repository with the app in which i made that video (it is not happening every time): https://github.com/BorislavStefanov31/legendListTestingEnv

**Comment by DheerajM-1** [comment]
same here on fast scrolling , UI shows blank screen

**Comment by jmeistrich** [comment]
@BorislavStefanov31 Huh, I just set up your repo (without changing anything) and I'm not seeing that at all 😱. I'm seeing the refresh spinner for a while, but the scroll length is not changing. And then all rendered items come in at once.

I wonder what the difference is?

**Comment by thestretivibity** [comment]
Impressive performance, but unfortunately we can't use it in production. There's too much blank space when it's used with infinite scrolling (loading more items upon reaching the end).

**Comment by OtavioStasiak** [comment]
I am facing the same issue here:
https://github.com/RocketChat/Rocket.Chat.ReactNative/tree/feat-migrate-to-legendlist

**Comment by BorislavStefanov31** [comment]
> [@BorislavStefanov31](https://github.com/BorislavStefanov31) Huh, I just set up your repo (without changing anything) and I'm not seeing that at all 😱. I'm seeing the refresh spinner for a while, but the scroll length is not changing. And then all rendered items come in at once.
> 
> I wonder what the difference is?

@jmeistrich Hello, sorry for taking so long to respond. I'm puzzled by the different behaviors we're seeing. I'll update the example to ensure consistent results and let you know when it's ready.

**Comment by OtavioStasiak** [comment]
@jmeistrich  Thanks for clarifying about extraData, it works as expected! However, the blanking behavior is still happening when running the app in release mode on the device (iPhone 13, iOS 18.4.1).

**Comment by jmeistrich** [comment]
I just released 1.0.11 - it's possible that changes since 1.0.9 fixed the blank at the end? But is that still happening in the repos you've shared with me? I've tested those repos in my simulator and everything looks fine, so I can't figure out what the difference is :(

**Comment by rahul-sysquare** [comment]
@jmeistrich I have also seen this issue when running on real device. here is my ticket https://github.com/LegendApp/legend-list/issues/231 although it started with something else but later I changed my code just to prevent glitchy UI and blank spaces but no luck yet.

**Comment by diegolmello** [comment]
@jmeistrich it's strange you can't reproduce this issue on your end.

One way we can do to keep the same behavior on the long run is running E2E tests on CI and recording those videos, but it requires a lot of work 😬

**Comment by jmeistrich** [comment]
I just released 1.0.12 which I am hopeful should fix this. How's it looking now?

**Comment by OtavioStasiak** [comment]
@jmeistrich  It still has the same behavior, and now it's crashing. I'm not sure what's going on when the package is built. I was looking through the repo and couldn't find anything that might be causing it.

However, when you install the library, in `node_modules/@legendapp/list/index.js` , on line 3 it has:

```
var React3 = require('react');
```

But for some reason, on line 551, inside the function `ListHeaderComponentContainer`, it's returning `React.createElement` instead of `React3.createElement`.

I was able to fix it temporarily using patch-package, but unfortunately, the blank space issue is still happening for me.

**Comment by jmeistrich** [comment]
@OtavioStasiak That's probably doing extremely weird things because you're reversing the list back and forth every time it adds new data. And you probably don't want to be reversing the array every time you update the list because that will be bad for performance. You probably want to just take that out. But if you really want to reverse the list before rendering it, clone it first so it doesn't modify the underlying array: `[...data].reverse()`

**Comment by OtavioStasiak** [comment]
@jmeistrich Sorry for the silly mistake, I got distracted... but using the reverse in a right way the blank area still happening as a video below.

https://github.com/user-attachments/assets/eb66f9f0-4d2f-435e-87fd-06a9df4e7f0b

**Comment by weiningtry7** [comment]
LOG You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.
I change
`      scrollEventThrottle: reactNative.Platform.OS === "web" ? 16 : void 0,
`
with 
`      scrollEventThrottle: reactNative.Platform.OS === "web" ? 16 : 16,
`
empty space disappear

**Comment by janroures** [comment]
this error is crazy, making onEndReached fire multiple times

**Comment by jmeistrich** [comment]
So sorry for the delay! I believe this should be fixed in the latest 3.0 beta versions (3.0.0-beta.55 as of now). Could you please give it another try and let me know if it's still a problem?
