### ISSUE TITLE
Scroll position is not maintained when `contentInset` values are modified

### ISSUE THREAD

**Issue by maxlapides** [LegendApp/legend-list#365]
## Description

When using `AnimatedLegendList` with both `alignItemsAtEnd={true}` and `maintainScrollAtEnd={true}`, setting a non-zero `contentInset.bottom` value via `animatedProps` causes the list to not properly maintain its scroll position at the end.

## Expected Behavior

When new items are added to the list, it should:
1. Automatically scroll to the end (due to `maintainScrollAtEnd`)
2. Account for the `contentInset.bottom` value when calculating the scroll position
3. Show the new item with the appropriate bottom spacing defined by `contentInset.bottom`

## Actual Behavior

When new items are added:
1. The list doesn't properly scroll to account for the `contentInset.bottom` value
2. New items may be partially cut off or not visible
3. The blank space defined by `contentInset.bottom` is not maintained

## Reproduction

1. Clone/download reproduction project: [legendlist-bug-reproduction.zip](https://github.com/user-attachments/files/23919235/legendlist-bug-reproduction.zip)
2. Run `npm install`
3. Run `npm run ios` or `npm run android`
4. Press "Set to 100" to set `contentInset.bottom` to 100px
6. **Observe:** The list is not scrolled with 100px more visible

## Use Case

This pattern is commonly needed in AI chat interfaces, as discussed in this article: [How we built the v0 iOS app](https://vercel.com/blog/how-we-built-the-v0-ios-app#scrolling-to-end-initially)

## Environment

```
@legendapp/list: latest
react-native-reanimated: ^3.x
react-native: via Expo
Platform: iOS/Android (both exhibit the issue)
```

## Workaround

Currently, we have to manually trigger scroll with a custom offset:

```typescript
listRef.current?.scrollToEnd?.({
  animated: false,
  viewOffset: -contentInsetBottom,
});
```

**Comment by jmeistrich** [comment]
@maxlapides I think this should be fixed in the latest beta. Can you try beta.15 and see if it's working better for you?

**Comment by GogaKler** [comment]
> [@maxlapides](https://github.com/maxlapides)I think this should be fixed in the latest beta. Can you try beta.15 and see if it's working better for you?

Hi! Quick update after testing on iOS.

### What works (beta.15+)
The fix in 3.0.0-beta.15 does work, but only when contentInset is passed as a regular prop

With this setup the list:
- scrolls to the bottom on the first render (via initialScrollIndex)
- and the initial scroll position correctly accounts for contentInset.bottom

```tsx
<AnimatedLegendList
  maintainVisibleContentPosition
  maintainScrollAtEnd
  initialScrollIndex={data.length ? data.length - 1 : 0}
  contentInset={{ bottom: contentInsetBottom }}
  data={data}
  renderItem={renderItem}
/>
```

### Still broken: contentInset via Reanimated animatedProps
If I move contentInset.bottom into Reanimated animatedProps, the first render no longer accounts for the inset (initial scroll lands “too low / wrong”):

```tsx
const animatedProps = useAnimatedProps(() => ({
  contentInset: { bottom: contentInsetBottom.value },
}));

<AnimatedLegendList
  maintainVisibleContentPosition
  maintainScrollAtEnd
  initialScrollIndex={data.length ? data.length - 1 : 0}
  animatedProps={animatedProps}
  data={data}
  renderItem={renderItem}
/>
```

### Workaround I’m using
Bridge the inset value from UI -> JS and pass it back as a plain contentInset prop:

```tsx
const [contentInsetBottomState, setContentInsetBottomState] = useState(0);

useAnimatedReaction(
  () => contentInsetBottom.value,
  (value) => {
    scheduleOnRN(setContentInsetBottomState, value);
  }
);

<AnimatedLegendList
  maintainVisibleContentPosition
  maintainScrollAtEnd
  initialScrollIndex={data.length ? data.length - 1 : 0}
  contentInset={{ bottom: contentInsetBottomState }}
  data={data}
  renderItem={renderItem}
/>
```

This gets me the expected initial scroll and correct bottom spacing without relying on animatedProps.

### Additional note: Reanimated v4 strict warning when using animatedProps
Whenever I pass animatedProps to AnimatedLegendList, I also get this warning:

```bash
WARN  [Reanimated] Reading from `value` during component render. Please ensure that you don't access the `value` property nor use `get` method of a shared value while React is rendering a component.
```

It happens even with an empty animatedProps:

```tsx
const animatedProps = useAnimatedProps(() => ({}));

<AnimatedLegendList
  maintainVisibleContentPosition
  maintainScrollAtEnd
  initialScrollIndex={data.length ? data.length - 1 : 0}
  animatedProps={animatedProps}
  data={data}
  renderItem={renderItem}
/>
```

I’m not 100% sure if that warning is caused by LegendList or the Reanimated animated-props pipeline on this setup, but it consistently reproduces as soon as animatedProps is provided.


### P.S
This is only fixed in v3.0.0-beta15. In v2, it still doesn't work, and I had to switch to the beta version to make contentInset work on the first render.

### dependencies
```json
{
    "react-native-worklets": "0.7.1",
    "react-native-reanimated": "~4.1.6",
    "@legendapp/list": "^3.0.0-beta.16"
}
```
